# Modelo LTR - Learning To Rank

In [1]:
import dagshub
import mlflow
from mlflow.models.signature import infer_signature

import polars as pl
import numpy as np
import json
from datetime import datetime

import lightgbm as lgb

from sklearn.model_selection import GroupShuffleSplit
from hyperopt import STATUS_OK, Trials, fmin, hp, tpe

from ml_utils import search_best_model


dagshub.init(repo_owner='abdala9512', repo_name='dsrp-machine-learning-engineering-4', mlflow=True)

/Users/miguelarquezabdala/repos/dsrp-machine-learning-engineering-4/notebooks/.venv/lib/python3.11/site-packages/hyperopt/atpe.py:19: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

Accessing as abdala9512

Initialized MLflow to track repo "abdala9512/dsrp-machine-learning-engineering-4"

Repository abdala9512/dsrp-machine-learning-engineering-4 initialized!

In [3]:
import numpy as np
import polars as pl


# -----------------------------------------------------------
# Utilidades para métricas de ranking
# -----------------------------------------------------------

def dcg(relevances):
    """Discounted Cumulative Gain."""
    relevances = np.array(relevances)
    discounts = 1 / np.log2(np.arange(2, len(relevances) + 2))
    return np.sum(relevances * discounts)


def ndcg_at_k(true_rels, pred_scores, k=10):
    """Compute NDCG@k for una query individual."""
    idx = np.argsort(-pred_scores)[:k]
    sorted_true = np.array(true_rels)[idx]

    dcg_k = dcg(sorted_true)

    # Ideal DCG (ordenamos relevâncias por orden descendente)
    ideal_sorted_true = np.sort(true_rels)[::-1][:k]
    idcg_k = dcg(ideal_sorted_true)

    return float( dcg_k / idcg_k if idcg_k > 0 else 0.0 )

## 1. Preparación de datos

In [4]:
# Cargar dataset sintético generado
DATASET_PATH = "data/ltr_synthetic_dataset.parquet"

ltr_df = pl.read_parquet(DATASET_PATH)
print(f"Dataset shape: {ltr_df.shape}")
print(f"Queries únicas: {ltr_df['query_id'].n_unique()}")
print(f"Distribución de labels:\n{ltr_df.group_by('label').len().sort('label')}")
ltr_df.head()

Dataset shape: (39000, 11)
Queries únicas: 390
Distribución de labels:
shape: (5, 2)
┌───────┬──────┐
│ label ┆ len  │
│ ---   ┆ ---  │
│ i32   ┆ u32  │
╞═══════╪══════╡
│ 0     ┆ 7800 │
│ 1     ┆ 7800 │
│ 2     ┆ 7800 │
│ 3     ┆ 7800 │
│ 4     ┆ 7800 │
└───────┴──────┘

shape: (5, 11)
┌──────────┬──────────────┬────────────┬──────────────┬───┬──────┬─────────────┬───────────┬───────┐
│ query_id ┆ query_text   ┆ imdb_id    ┆ title        ┆ … ┆ year ┆ genres      ┆ rel_score ┆ label │
│ ---      ┆ ---          ┆ ---        ┆ ---          ┆   ┆ ---  ┆ ---         ┆ ---       ┆ ---   │
│ i32      ┆ str          ┆ str        ┆ str          ┆   ┆ i32  ┆ str         ┆ f64       ┆ i32   │
╞══════════╪══════════════╪════════════╪══════════════╪═══╪══════╪═════════════╪═══════════╪═══════╡
│ 1        ┆ best drama   ┆ tt18163024 ┆ Chaaruseela  ┆ … ┆ 2022 ┆ null        ┆ 0.627926  ┆ 4     │
│          ┆ movies with  ┆            ┆              ┆   ┆      ┆             ┆           ┆       │
│          ┆ complex…     ┆            ┆              ┆   ┆      ┆             ┆           ┆       │
│ 1        ┆ best drama   ┆ tt2243299  ┆ Final Cut:   ┆ … ┆ 2012 ┆ Comedy,Dram ┆ 0.627141  ┆ 4     │
│          ┆ movies with  ┆            ┆ Ladies and   ┆   ┆      ┆ a,Romance   ┆           ┆       │
│          ┆ complex…     ┆            ┆ Gentleme…    ┆   ┆      ┆             ┆           ┆       │
│ 1        ┆ best drama   ┆ tt0100998  ┆ Dreams       ┆ … ┆ 1990 ┆ Drama,Fanta ┆ 0.624123  ┆ 4     │
│          ┆ movies with  ┆            ┆              ┆   ┆      ┆ sy          ┆           ┆       │
│          ┆ complex…     ┆            ┆              ┆   ┆      ┆             ┆           ┆       │
│ 1        ┆ best drama   ┆ tt1895484  ┆ Model        ┆ … ┆ 2012 ┆ Drama       ┆ 0.620467  ┆ 4     │
│          ┆ movies with  ┆            ┆ Minority     ┆   ┆      ┆             ┆           ┆       │
│          ┆ complex…     ┆            ┆              ┆   ┆      ┆             ┆           ┆       │
│ 1        ┆ best drama   ┆ tt2245544  ┆ Carry on     ┆ … ┆ 2012 ┆ Comedy      ┆ 0.618704  ┆ 4     │
│          ┆ movies with  ┆            ┆ Jatta        ┆   ┆      ┆             ┆           ┆       │
│          ┆ complex…     ┆            ┆              ┆   ┆      ┆             ┆           ┆       │
└──────────┴──────────────┴────────────┴──────────────┴───┴──────┴─────────────┴───────────┴───────┘

In [5]:
# Columnas de features
feature_cols = [c for c in ltr_df.columns if c.startswith("emb_")] + [
    "sim_embedding",
    "imdb_rating",
    "imdb_votes_log",
]

# Filtrar solo las columnas que existen en el dataset
feature_cols = [c for c in feature_cols if c in ltr_df.columns]
print(f"Features utilizadas: {feature_cols}")

# Preparar datos
X = ltr_df.select(feature_cols).to_numpy()
y = ltr_df["label"].to_numpy()
query_ids = ltr_df["query_id"].to_numpy()

# Calcular grupos (cantidad de docs por query)
groups = ltr_df.group_by("query_id", maintain_order=True).len()["len"].to_numpy()

print(f"X shape: {X.shape}")
print(f"y shape: {y.shape}")
print(f"Num groups: {len(groups)}")

Features utilizadas: ['sim_embedding', 'imdb_rating', 'imdb_votes_log']
X shape: (39000, 3)
y shape: (39000,)
Num groups: 390

In [6]:
# Split por queries (80% train, 20% test)
TEST_SIZE = 0.2
RANDOM_STATE = 42

qid_list = ltr_df["query_id"].unique().to_list()
np.random.seed(RANDOM_STATE)
np.random.shuffle(qid_list)

split_idx = int(len(qid_list) * (1 - TEST_SIZE))
train_ids = qid_list[:split_idx]
test_ids = qid_list[split_idx:]

print(f"Train queries: {len(train_ids)}, Test queries: {len(test_ids)}")

# Filtrar datasets
ltr_train = ltr_df.filter(pl.col("query_id").is_in(train_ids))
ltr_test = ltr_df.filter(pl.col("query_id").is_in(test_ids))

# Preparar arrays
X_train = ltr_train.select(feature_cols).to_numpy()
y_train = ltr_train["label"].to_numpy()
train_groups = ltr_train.group_by("query_id", maintain_order=True).len()["len"].to_numpy()

X_test = ltr_test.select(feature_cols).to_numpy()
y_test = ltr_test["label"].to_numpy()
test_groups = ltr_test.group_by("query_id", maintain_order=True).len()["len"].to_numpy()
test_query_ids = ltr_test["query_id"].to_numpy()

print(f"Train samples: {X_train.shape[0]}, Test samples: {X_test.shape[0]}")

Train queries: 312, Test queries: 78
Train samples: 31200, Test samples: 7800

In [7]:
# Espacio de búsqueda expandido
search_space = {
    "max_depth": hp.quniform("max_depth", 3, 12, 1),
    "n_estimators": hp.quniform("n_estimators", 50, 500, 50),
    "learning_rate": hp.loguniform("learning_rate", np.log(0.01), np.log(0.3)),
    "num_leaves": hp.quniform("num_leaves", 15, 127, 1),
    "min_child_samples": hp.quniform("min_child_samples", 5, 50, 5),
    "subsample": hp.uniform("subsample", 0.6, 1.0),
    "colsample_bytree": hp.uniform("colsample_bytree", 0.6, 1.0),
    "reg_alpha": hp.loguniform("reg_alpha", np.log(1e-8), np.log(10.0)),
    "reg_lambda": hp.loguniform("reg_lambda", np.log(1e-8), np.log(10.0)),
}

def objective(params):
    """Función objetivo para Hyperopt."""
    normalized_params = {
        "max_depth": int(params["max_depth"]),
        "n_estimators": int(params["n_estimators"]),
        "learning_rate": params["learning_rate"],
        "num_leaves": int(params["num_leaves"]),
        "min_child_samples": int(params["min_child_samples"]),
        "subsample": params["subsample"],
        "colsample_bytree": params["colsample_bytree"],
        "reg_alpha": params["reg_alpha"],
        "reg_lambda": params["reg_lambda"],
    }

    ranker = lgb.LGBMRanker(
        objective="lambdarank",
        boosting_type="gbdt",
        metric="ndcg",
        verbose=-1,
        **normalized_params
    )
    
    ranker.fit(
        X_train,
        y_train,
        group=train_groups
    )

    predictions = ranker.predict(X_test)
    
    # Calcular NDCG promedio por query
    ndcg_scores = []
    idx = 0
    for g in test_groups:
        y_true_q = y_test[idx:idx+g]
        preds_q = predictions[idx:idx+g]
        ndcg_scores.append(ndcg_at_k(y_true_q, preds_q, k=10))
        idx += g
    
    mean_ndcg = np.mean(ndcg_scores)
    print(f"Mean nDCG@10: {mean_ndcg:.4f}")
    
    return {"loss": -mean_ndcg, "status": STATUS_OK}

# Ejecutar búsqueda de hiperparámetros
MAX_EVALS = 15
trials = Trials()

print(f"Iniciando búsqueda de hiperparámetros ({MAX_EVALS} evaluaciones)...")
BEST_PARAMS = fmin(
    fn=objective,
    space=search_space,
    algo=tpe.suggest,
    trials=trials,
    max_evals=MAX_EVALS,
)

print(f"\nMejores parámetros encontrados:")
BEST_PARAMS

Iniciando búsqueda de hiperparámetros (15 evaluaciones)...
  0%|          | 0/15 [00:00<?, ?trial/s, best loss=?]

Mean nDCG@10: 0.9971
  7%|▋         | 1/15 [00:03<00:46,  3.36s/trial, best loss: -0.9971343965855212]

/Users/miguelarquezabdala/repos/dsrp-machine-learning-engineering-4/notebooks/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRanker was fitted with feature names
  warnings.warn(

Mean nDCG@10: 0.9972
 13%|█▎        | 2/15 [00:03<00:22,  1.70s/trial, best loss: -0.997191773184083]

/Users/miguelarquezabdala/repos/dsrp-machine-learning-engineering-4/notebooks/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRanker was fitted with feature names
  warnings.warn(

Mean nDCG@10: 0.9969
 20%|██        | 3/15 [00:07<00:32,  2.72s/trial, best loss: -0.997191773184083]

/Users/miguelarquezabdala/repos/dsrp-machine-learning-engineering-4/notebooks/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRanker was fitted with feature names
  warnings.warn(

Mean nDCG@10: 0.9978
 27%|██▋       | 4/15 [00:09<00:24,  2.19s/trial, best loss: -0.9978365935916642]

/Users/miguelarquezabdala/repos/dsrp-machine-learning-engineering-4/notebooks/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRanker was fitted with feature names
  warnings.warn(

Mean nDCG@10: 0.9979
 33%|███▎      | 5/15 [00:10<00:16,  1.69s/trial, best loss: -0.9979465633366171]

/Users/miguelarquezabdala/repos/dsrp-machine-learning-engineering-4/notebooks/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRanker was fitted with feature names
  warnings.warn(

Mean nDCG@10: 0.9972
 40%|████      | 6/15 [00:12<00:17,  1.91s/trial, best loss: -0.9979465633366171]

/Users/miguelarquezabdala/repos/dsrp-machine-learning-engineering-4/notebooks/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRanker was fitted with feature names
  warnings.warn(

Mean nDCG@10: 0.9973
 47%|████▋     | 7/15 [00:12<00:11,  1.44s/trial, best loss: -0.9979465633366171]

/Users/miguelarquezabdala/repos/dsrp-machine-learning-engineering-4/notebooks/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRanker was fitted with feature names
  warnings.warn(

Mean nDCG@10: 0.9983
 53%|█████▎    | 8/15 [00:15<00:12,  1.73s/trial, best loss: -0.9982545365073758]

/Users/miguelarquezabdala/repos/dsrp-machine-learning-engineering-4/notebooks/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRanker was fitted with feature names
  warnings.warn(

Mean nDCG@10: 0.9974
 60%|██████    | 9/15 [00:15<00:07,  1.30s/trial, best loss: -0.9982545365073758]

/Users/miguelarquezabdala/repos/dsrp-machine-learning-engineering-4/notebooks/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRanker was fitted with feature names
  warnings.warn(

Mean nDCG@10: 0.9978
 67%|██████▋   | 10/15 [00:17<00:06,  1.37s/trial, best loss: -0.9982545365073758]

/Users/miguelarquezabdala/repos/dsrp-machine-learning-engineering-4/notebooks/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRanker was fitted with feature names
  warnings.warn(

Mean nDCG@10: 0.9976
 73%|███████▎  | 11/15 [00:20<00:08,  2.14s/trial, best loss: -0.9982545365073758]

/Users/miguelarquezabdala/repos/dsrp-machine-learning-engineering-4/notebooks/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRanker was fitted with feature names
  warnings.warn(

Mean nDCG@10: 0.9977
 80%|████████  | 12/15 [00:21<00:04,  1.65s/trial, best loss: -0.9982545365073758]

/Users/miguelarquezabdala/repos/dsrp-machine-learning-engineering-4/notebooks/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRanker was fitted with feature names
  warnings.warn(

Mean nDCG@10: 0.9976
 87%|████████▋ | 13/15 [00:24<00:03,  1.95s/trial, best loss: -0.9982545365073758]

/Users/miguelarquezabdala/repos/dsrp-machine-learning-engineering-4/notebooks/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRanker was fitted with feature names
  warnings.warn(

Mean nDCG@10: 0.9973
 93%|█████████▎| 14/15 [00:28<00:02,  2.65s/trial, best loss: -0.9982545365073758]

/Users/miguelarquezabdala/repos/dsrp-machine-learning-engineering-4/notebooks/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRanker was fitted with feature names
  warnings.warn(

Mean nDCG@10: 0.9941
100%|██████████| 15/15 [00:28<00:00,  1.91s/trial, best loss: -0.9982545365073758]

Mejores parámetros encontrados:

/Users/miguelarquezabdala/repos/dsrp-machine-learning-engineering-4/notebooks/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRanker was fitted with feature names
  warnings.warn(

{'colsample_bytree': np.float64(0.9691945093617281),
 'learning_rate': np.float64(0.21728293815047925),
 'max_depth': np.float64(11.0),
 'min_child_samples': np.float64(25.0),
 'n_estimators': np.float64(450.0),
 'num_leaves': np.float64(90.0),
 'reg_alpha': np.float64(2.052112020987347e-05),
 'reg_lambda': np.float64(7.815915352316542),
 'subsample': np.float64(0.84576205137197)}

In [8]:
# Normalizar mejores parámetros
best_params = {
    "max_depth": int(BEST_PARAMS["max_depth"]),
    "n_estimators": int(BEST_PARAMS["n_estimators"]),
    "learning_rate": BEST_PARAMS["learning_rate"],
    "num_leaves": int(BEST_PARAMS["num_leaves"]),
    "min_child_samples": int(BEST_PARAMS["min_child_samples"]),
    "subsample": BEST_PARAMS["subsample"],
    "colsample_bytree": BEST_PARAMS["colsample_bytree"],
    "reg_alpha": BEST_PARAMS["reg_alpha"],
    "reg_lambda": BEST_PARAMS["reg_lambda"],
}

print("Parámetros optimizados:")
for k, v in best_params.items():
    print(f"  {k}: {v}")

Parámetros optimizados:
  max_depth: 11
  n_estimators: 450
  learning_rate: 0.21728293815047925
  num_leaves: 90
  min_child_samples: 25
  subsample: 0.84576205137197
  colsample_bytree: 0.9691945093617281
  reg_alpha: 2.052112020987347e-05
  reg_lambda: 7.815915352316542

In [9]:
# Configurar experimento (get_or_create para evitar errores en múltiples ejecuciones)
EXPERIMENT_NAME = "LTR - Synthetic Queries Dataset"

experiment = mlflow.get_experiment_by_name(EXPERIMENT_NAME)
if experiment is None:
    experiment_id = mlflow.create_experiment(EXPERIMENT_NAME)
    print(f"Experimento '{EXPERIMENT_NAME}' creado con ID: {experiment_id}")
else:
    experiment_id = experiment.experiment_id
    print(f"Experimento '{EXPERIMENT_NAME}' encontrado con ID: {experiment_id}")

mlflow.set_experiment(EXPERIMENT_NAME)

Experimento 'LTR - Synthetic Queries Dataset' encontrado con ID: 3

<Experiment: artifact_location='mlflow-artifacts:/d380128d2c514b68b28a91f8085dd39e', creation_time=1768105756500, experiment_id='3', last_update_time=1768105756500, lifecycle_stage='active', name='LTR - Synthetic Queries Dataset', tags={}>

In [10]:
MODEL_NAME = "ltr-dsrpflix-prd"
RUN_NAME = f"LGBM Ranker - {datetime.now().strftime('%Y%m%d_%H%M%S')}"

def compute_metrics_per_query(y_true, predictions, groups, ks=[5, 10, 15, 20]):
    """Calcular métricas NDCG por query y promediar."""
    metrics = {f"nDCG_{k}": [] for k in ks}  # Usar underscore en lugar de @
    
    idx = 0
    for g in groups:
        y_true_q = y_true[idx:idx+g]
        preds_q = predictions[idx:idx+g]
        
        for k in ks:
            metrics[f"nDCG_{k}"].append(ndcg_at_k(y_true_q, preds_q, k=k))
        idx += g
    
    return {k: np.mean(v) for k, v in metrics.items()}

with mlflow.start_run(run_name=RUN_NAME) as run:
    
    # ============= Entrenar modelo final =============
    final_ranker = lgb.LGBMRanker(
        objective="lambdarank",
        boosting_type="gbdt",
        metric="ndcg",
        verbose=-1,
        **best_params
    )
    
    final_ranker.fit(
        X_train,
        y_train,
        group=train_groups
    )
    
    # ============= Predicciones y métricas =============
    train_predictions = final_ranker.predict(X_train)
    test_predictions = final_ranker.predict(X_test)
    
    # Métricas en train y test
    train_metrics = compute_metrics_per_query(y_train, train_predictions, train_groups)
    test_metrics = compute_metrics_per_query(y_test, test_predictions, test_groups)
    
    # ============= Logging de parámetros =============
    mlflow.log_params(best_params)
    mlflow.log_params({
        "dataset_path": DATASET_PATH,
        "test_size": TEST_SIZE,
        "random_state": RANDOM_STATE,
        "num_features": len(feature_cols),
        "feature_names": ",".join(feature_cols),
        "train_queries": len(train_ids),
        "test_queries": len(test_ids),
        "train_samples": X_train.shape[0],
        "test_samples": X_test.shape[0],
        "hyperopt_max_evals": MAX_EVALS,
    })
    
    # ============= Logging de métricas =============
    # Métricas de test (principales)
    for metric_name, value in test_metrics.items():
        mlflow.log_metric(f"test_{metric_name}", value)
    
    # Métricas de train (para detectar overfitting)
    for metric_name, value in train_metrics.items():
        mlflow.log_metric(f"train_{metric_name}", value)
    
    # Métricas adicionales
    mlflow.log_metric("train_test_ndcg10_gap", train_metrics["nDCG_10"] - test_metrics["nDCG_10"])
    
    # ============= Feature Importance =============
    feature_importance = dict(zip(feature_cols, final_ranker.feature_importances_.tolist()))
    
    # Guardar como artifact JSON
    with open("feature_importance.json", "w") as f:
        json.dump(feature_importance, f, indent=2)
    mlflow.log_artifact("feature_importance.json")
    
    # Log individual feature importances como métricas
    for feat, imp in feature_importance.items():
        mlflow.log_metric(f"feat_imp_{feat}", imp)
    
    # ============= Guardar modelo =============
    signature = infer_signature(X_train, train_predictions)
    
    mlflow.lightgbm.log_model(
        lgb_model=final_ranker, 
        artifact_path="model",
        signature=signature,
        input_example=X_train[:5],
        registered_model_name=MODEL_NAME,
    )
    
    # ============= Artifacts adicionales =============
    # Guardar configuración del experimento
    experiment_config = {
        "dataset_path": DATASET_PATH,
        "feature_cols": feature_cols,
        "best_params": best_params,
        "train_metrics": train_metrics,
        "test_metrics": test_metrics,
        "timestamp": datetime.now().isoformat(),
    }
    
    with open("experiment_config.json", "w") as f:
        json.dump(experiment_config, f, indent=2, default=str)
    mlflow.log_artifact("experiment_config.json")
    
    # ============= Resumen =============
    print("\n" + "="*60)
    print("RESUMEN DEL ENTRENAMIENTO")
    print("="*60)
    print(f"\nMétricas de Test:")
    for k, v in test_metrics.items():
        print(f"  {k}: {v:.4f}")
    
    print(f"\nMétricas de Train:")
    for k, v in train_metrics.items():
        print(f"  {k}: {v:.4f}")
    
    print(f"\nOverfitting gap (train - test nDCG_10): {train_metrics['nDCG_10'] - test_metrics['nDCG_10']:.4f}")
    print(f"\nRun ID: {run.info.run_id}")
    print(f"Modelo registrado: {MODEL_NAME}")

/Users/miguelarquezabdala/repos/dsrp-machine-learning-engineering-4/notebooks/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRanker was fitted with feature names
  warnings.warn(
/Users/miguelarquezabdala/repos/dsrp-machine-learning-engineering-4/notebooks/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRanker was fitted with feature names
  warnings.warn(
2026/01/10 23:41:19 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/01/10 23:41:39 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
/Users/miguelarquezabdala/repos/dsrp-machine-learning-engineering-4/notebooks/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRanker was fitted with feature names
  warnings.warn(
Registered model 'ltr-dsrpflix-prd' already exists. Creating a new version of this model...
2026/01/10 23:41:47 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: ltr-dsrpflix-prd, version 5
Created version '5' of model 'ltr-dsrpflix-prd'.

============================================================
RESUMEN DEL ENTRENAMIENTO
============================================================

Métricas de Test:
  nDCG_5: 1.0000
  nDCG_10: 0.9983
  nDCG_15: 0.9922
  nDCG_20: 0.9769

Métricas de Train:
  nDCG_5: 1.0000
  nDCG_10: 0.9995
  nDCG_15: 0.9951
  nDCG_20: 0.9827

Overfitting gap (train - test nDCG_10): 0.0013

Run ID: 709fb5fd83a245f1951723770deba194
Modelo registrado: ltr-dsrpflix-prd
🏃 View run LGBM Ranker - 20260110_234110 at: https://dagshub.com/abdala9512/dsrp-machine-learning-engineering-4.mlflow/#/experiments/3/runs/709fb5fd83a245f1951723770deba194
🧪 View experiment at: https://dagshub.com/abdala9512/dsrp-machine-learning-engineering-4.mlflow/#/experiments/3

In [11]:
# Promoción automática del modelo (Champion/Challenger)
METRIC_TO_COMPARE = "test_nDCG_10"  # Usar underscore en lugar de @

client = mlflow.MlflowClient()

try:
    registered_model = client.get_registered_model(name=MODEL_NAME)
    
    # Obtener última versión
    latest_version = registered_model.latest_versions[0].version
    latest_run_id = registered_model.latest_versions[0].run_id
    latest_metric = mlflow.get_run(run_id=latest_run_id).data.metrics.get(METRIC_TO_COMPARE, 0)
    
    print(f"Última versión del modelo: v{latest_version}")
    print(f"  {METRIC_TO_COMPARE}: {latest_metric:.4f}")
    
    # Verificar si existe champion
    if "champion" in registered_model.aliases:
        champion_version = registered_model.aliases["champion"]
        champion_run_id = client.get_model_version(name=MODEL_NAME, version=champion_version).run_id
        champion_metric = mlflow.get_run(run_id=champion_run_id).data.metrics.get(METRIC_TO_COMPARE, 0)
        
        print(f"\nChampion actual: v{champion_version}")
        print(f"  {METRIC_TO_COMPARE}: {champion_metric:.4f}")
        
        if latest_version != champion_version:
            if latest_metric >= champion_metric:
                client.set_registered_model_alias(
                    name=MODEL_NAME,
                    alias="champion",
                    version=latest_version
                )
                # Marcar versión anterior como challenger
                client.set_registered_model_alias(
                    name=MODEL_NAME,
                    alias="previous_champion",
                    version=champion_version
                )
                print(f"\n✅ Modelo v{latest_version} promovido a CHAMPION (mejora de {latest_metric - champion_metric:.4f})")
            else:
                client.set_registered_model_alias(
                    name=MODEL_NAME,
                    alias="challenger",
                    version=latest_version
                )
                print(f"\n⚠️ Modelo v{latest_version} marcado como CHALLENGER (inferior al champion por {champion_metric - latest_metric:.4f})")
        else:
            print("\n✅ La última versión ya es el champion")
    else:
        # No hay champion, promover la última versión
        client.set_registered_model_alias(
            name=MODEL_NAME,
            alias="champion",
            version=latest_version
        )
        print(f"\n✅ Modelo v{latest_version} establecido como primer CHAMPION")

except Exception as e:
    print(f"Error al gestionar modelo: {e}")

Última versión del modelo: v5
  test_nDCG_10: 0.9983

Champion actual: v4
  test_nDCG_10: 0.0000

✅ Modelo v5 promovido a CHAMPION (mejora de 0.9983)

In [12]:
# Cargar modelo champion para inferencia
print(f"Cargando modelo champion: {MODEL_NAME}@champion")
prod_model = mlflow.lightgbm.load_model(f"models:/{MODEL_NAME}@champion")
print("Modelo cargado exitosamente")

Cargando modelo champion: ltr-dsrpflix-prd@champion

/Users/miguelarquezabdala/repos/dsrp-machine-learning-engineering-4/notebooks/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Downloading artifacts: 100%|██████████| 7/7 [00:01<00:00,  3.75it/s]

Modelo cargado exitosamente

In [13]:
def test_single_query(qid: int, model, df: pl.DataFrame = ltr_df) -> pl.DataFrame:
    """Probar el modelo con una query específica."""
    query_df = df.filter(pl.col("query_id") == qid)
    
    if query_df.is_empty():
        print(f"Query ID {qid} no encontrada")
        return None
    
    X_query = query_df.select(feature_cols).to_numpy()
    preds = model.predict(X_query)
    
    result = query_df.with_columns(pl.Series("ranker_score", preds))
    result = result.sort("ranker_score", descending=True)
    
    query_text = result["query_text"][0]
    print(f"Query: '{query_text}'")
    print(f"Resultados ordenados por ranker_score:\n")
    
    return result.select([
        "query_id", "query_text", "title", "genres", 
        "imdb_rating", "sim_embedding", "ranker_score", "label"
    ]).head(10)

# Probar con algunas queries
sample_query_ids = ltr_df["query_id"].unique().to_list()[:3]
for qid in sample_query_ids:
    print("="*60)
    display(test_single_query(qid, model=prod_model))
    print()

============================================================
Query: 'best drama movies with complex female characters'
Resultados ordenados por ranker_score:

/Users/miguelarquezabdala/repos/dsrp-machine-learning-engineering-4/notebooks/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRanker was fitted with feature names
  warnings.warn(

shape: (10, 8)
┌──────────┬─────────────┬─────────────┬────────────┬────────────┬────────────┬────────────┬───────┐
│ query_id ┆ query_text  ┆ title       ┆ genres     ┆ imdb_ratin ┆ sim_embedd ┆ ranker_sco ┆ label │
│ ---      ┆ ---         ┆ ---         ┆ ---        ┆ g          ┆ ing        ┆ re         ┆ ---   │
│ i32      ┆ str         ┆ str         ┆ str        ┆ ---        ┆ ---        ┆ ---        ┆ i32   │
│          ┆             ┆             ┆            ┆ f64        ┆ f32        ┆ f64        ┆       │
╞══════════╪═════════════╪═════════════╪════════════╪════════════╪════════════╪════════════╪═══════╡
│ 1        ┆ best drama  ┆ Dreams      ┆ Drama,Fant ┆ 7.7        ┆ 0.444638   ┆ 8.568286   ┆ 4     │
│          ┆ movies with ┆             ┆ asy        ┆            ┆            ┆            ┆       │
│          ┆ complex…    ┆             ┆            ┆            ┆            ┆            ┆       │
│ 1        ┆ best drama  ┆ Laurence    ┆ Drama,Roma ┆ 7.6        ┆ 0.446079   ┆ 7.182148   ┆ 4     │
│          ┆ movies with ┆ Anyways     ┆ nce        ┆            ┆            ┆            ┆       │
│          ┆ complex…    ┆             ┆            ┆            ┆            ┆            ┆       │
│ 1        ┆ best drama  ┆ My Girl     ┆ Comedy,Dra ┆ 6.9        ┆ 0.459826   ┆ 6.641594   ┆ 4     │
│          ┆ movies with ┆             ┆ ma,Family  ┆            ┆            ┆            ┆       │
│          ┆ complex…    ┆             ┆            ┆            ┆            ┆            ┆       │
│ 1        ┆ best drama  ┆ The Match   ┆ Comedy,Cri ┆ 7.5        ┆ 0.462694   ┆ 5.976734   ┆ 4     │
│          ┆ movies with ┆ Factory     ┆ me,Drama   ┆            ┆            ┆            ┆       │
│          ┆ complex…    ┆ Girl        ┆            ┆            ┆            ┆            ┆       │
│ 1        ┆ best drama  ┆ Tokyo       ┆ Drama      ┆ 8.0        ┆ 0.453766   ┆ 5.334163   ┆ 4     │
│          ┆ movies with ┆ Twilight    ┆            ┆            ┆            ┆            ┆       │
│          ┆ complex…    ┆             ┆            ┆            ┆            ┆            ┆       │
│ 1        ┆ best drama  ┆ Carry on    ┆ Comedy     ┆ 8.3        ┆ 0.441478   ┆ 4.890681   ┆ 4     │
│          ┆ movies with ┆ Jatta       ┆            ┆            ┆            ┆            ┆       │
│          ┆ complex…    ┆             ┆            ┆            ┆            ┆            ┆       │
│ 1        ┆ best drama  ┆ The Girls   ┆ Comedy,Rom ┆ 7.8        ┆ 0.439745   ┆ 4.871431   ┆ 4     │
│          ┆ movies with ┆             ┆ ance       ┆            ┆            ┆            ┆       │
│          ┆ complex…    ┆             ┆            ┆            ┆            ┆            ┆       │
│ 1        ┆ best drama  ┆ Awe!        ┆ Drama,Fant ┆ 7.6        ┆ 0.485805   ┆ 4.722508   ┆ 4     │
│          ┆ movies with ┆             ┆ asy,Horror ┆            ┆            ┆            ┆       │
│          ┆ complex…    ┆             ┆            ┆            ┆            ┆            ┆       │
│ 1        ┆ best drama  ┆ Final Cut:  ┆ Comedy,Dra ┆ 8.0        ┆ 0.501051   ┆ 4.577163   ┆ 4     │
│          ┆ movies with ┆ Ladies and  ┆ ma,Romance ┆            ┆            ┆            ┆       │
│          ┆ complex…    ┆ Gentleme…   ┆            ┆            ┆            ┆            ┆       │
│ 1        ┆ best drama  ┆ Zero 2      ┆ Comedy,Thr ┆ 7.5        ┆ 0.489139   ┆ 4.456155   ┆ 4     │
│          ┆ movies with ┆             ┆ iller      ┆            ┆            ┆            ┆       │
│          ┆ complex…    ┆             ┆            ┆            ┆            ┆            ┆       │
└──────────┴─────────────┴─────────────┴────────────┴────────────┴────────────┴────────────┴───────┘

============================================================
Query: 'emotional films that make me cry'
Resultados ordenados por ranker_score:

/Users/miguelarquezabdala/repos/dsrp-machine-learning-engineering-4/notebooks/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRanker was fitted with feature names
  warnings.warn(

shape: (10, 8)
┌──────────┬─────────────┬─────────────┬────────────┬────────────┬────────────┬────────────┬───────┐
│ query_id ┆ query_text  ┆ title       ┆ genres     ┆ imdb_ratin ┆ sim_embedd ┆ ranker_sco ┆ label │
│ ---      ┆ ---         ┆ ---         ┆ ---        ┆ g          ┆ ing        ┆ re         ┆ ---   │
│ i32      ┆ str         ┆ str         ┆ str        ┆ ---        ┆ ---        ┆ ---        ┆ i32   │
│          ┆             ┆             ┆            ┆ f64        ┆ f32        ┆ f64        ┆       │
╞══════════╪═════════════╪═════════════╪════════════╪════════════╪════════════╪════════════╪═══════╡
│ 2        ┆ emotional   ┆ Dreams      ┆ Drama,Fant ┆ 7.7        ┆ 0.541024   ┆ 9.198353   ┆ 4     │
│          ┆ films that  ┆             ┆ asy        ┆            ┆            ┆            ┆       │
│          ┆ make me c…  ┆             ┆            ┆            ┆            ┆            ┆       │
│ 2        ┆ emotional   ┆ Pain and    ┆ Drama      ┆ 7.5        ┆ 0.474234   ┆ 8.467851   ┆ 4     │
│          ┆ films that  ┆ Glory       ┆            ┆            ┆            ┆            ┆       │
│          ┆ make me c…  ┆             ┆            ┆            ┆            ┆            ┆       │
│ 2        ┆ emotional   ┆ Violet      ┆ Animation, ┆ 8.3        ┆ 0.486872   ┆ 7.844341   ┆ 4     │
│          ┆ films that  ┆ Evergarden: ┆ Drama,Fant ┆            ┆            ┆            ┆       │
│          ┆ make me c…  ┆ The Movie   ┆ asy        ┆            ┆            ┆            ┆       │
│ 2        ┆ emotional   ┆ Stanley     ┆ Biography, ┆ 8.0        ┆ 0.446199   ┆ 7.653883   ┆ 4     │
│          ┆ films that  ┆ Kubrick: A  ┆ Documentar ┆            ┆            ┆            ┆       │
│          ┆ make me c…  ┆ Life in     ┆ y          ┆            ┆            ┆            ┆       │
│          ┆             ┆ Pic…        ┆            ┆            ┆            ┆            ┆       │
│ 2        ┆ emotional   ┆ The 100     ┆ Action     ┆ 7.4        ┆ 0.630272   ┆ 6.859555   ┆ 4     │
│          ┆ films that  ┆             ┆            ┆            ┆            ┆            ┆       │
│          ┆ make me c…  ┆             ┆            ┆            ┆            ┆            ┆       │
│ 2        ┆ emotional   ┆ Aruvi       ┆ Drama      ┆ 8.3        ┆ 0.414647   ┆ 6.849975   ┆ 4     │
│          ┆ films that  ┆             ┆            ┆            ┆            ┆            ┆       │
│          ┆ make me c…  ┆             ┆            ┆            ┆            ┆            ┆       │
│ 2        ┆ emotional   ┆ The Wishing ┆ Drama      ┆ 8.0        ┆ 0.521648   ┆ 4.58606    ┆ 4     │
│          ┆ films that  ┆ Tree        ┆            ┆            ┆            ┆            ┆       │
│          ┆ make me c…  ┆             ┆            ┆            ┆            ┆            ┆       │
│ 2        ┆ emotional   ┆ Boys Don't  ┆ Comedy,Cri ┆ 7.6        ┆ 0.430004   ┆ 3.965287   ┆ 4     │
│          ┆ films that  ┆ Cry         ┆ me         ┆            ┆            ┆            ┆       │
│          ┆ make me c…  ┆             ┆            ┆            ┆            ┆            ┆       │
│ 2        ┆ emotional   ┆ Love and    ┆ Drama,Roma ┆ 7.8        ┆ 0.47853    ┆ 3.251424   ┆ 4     │
│          ┆ films that  ┆ Lies        ┆ nce        ┆            ┆            ┆            ┆       │
│          ┆ make me c…  ┆             ┆            ┆            ┆            ┆            ┆       │
│ 2        ┆ emotional   ┆ Cries from  ┆ Documentar ┆ 8.3        ┆ 0.476482   ┆ 3.236857   ┆ 4     │
│          ┆ films that  ┆ Syria       ┆ y,Drama,Wa ┆            ┆            ┆            ┆       │
│          ┆ make me c…  ┆             ┆ r          ┆            ┆            ┆            ┆       │
└──────────┴─────────────┴─────────────┴────────────┴────────────┴────────────┴────────────┴───────┘

============================================================
Query: 'similar to 12 years a slave but more hopeful'
Resultados ordenados por ranker_score:

/Users/miguelarquezabdala/repos/dsrp-machine-learning-engineering-4/notebooks/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRanker was fitted with feature names
  warnings.warn(

shape: (10, 8)
┌──────────┬─────────────┬─────────────┬────────────┬────────────┬────────────┬────────────┬───────┐
│ query_id ┆ query_text  ┆ title       ┆ genres     ┆ imdb_ratin ┆ sim_embedd ┆ ranker_sco ┆ label │
│ ---      ┆ ---         ┆ ---         ┆ ---        ┆ g          ┆ ing        ┆ re         ┆ ---   │
│ i32      ┆ str         ┆ str         ┆ str        ┆ ---        ┆ ---        ┆ ---        ┆ i32   │
│          ┆             ┆             ┆            ┆ f64        ┆ f32        ┆ f64        ┆       │
╞══════════╪═════════════╪═════════════╪════════════╪════════════╪════════════╪════════════╪═══════╡
│ 3        ┆ similar to  ┆ 12 Years a  ┆ Biography, ┆ 8.1        ┆ 0.519383   ┆ 9.404646   ┆ 4     │
│          ┆ 12 years a  ┆ Slave       ┆ Drama,Hist ┆            ┆            ┆            ┆       │
│          ┆ slave bu…   ┆             ┆ ory        ┆            ┆            ┆            ┆       │
│ 3        ┆ similar to  ┆ Amistad     ┆ Biography, ┆ 7.3        ┆ 0.427629   ┆ 7.09198    ┆ 4     │
│          ┆ 12 years a  ┆             ┆ Drama,Hist ┆            ┆            ┆            ┆       │
│          ┆ slave bu…   ┆             ┆ ory        ┆            ┆            ┆            ┆       │
│ 3        ┆ similar to  ┆ Lincoln     ┆ Biography, ┆ 7.3        ┆ 0.369265   ┆ 4.451942   ┆ 4     │
│          ┆ 12 years a  ┆             ┆ Drama,Hist ┆            ┆            ┆            ┆       │
│          ┆ slave bu…   ┆             ┆ ory        ┆            ┆            ┆            ┆       │
│ 3        ┆ similar to  ┆ Fantastic   ┆ Animation, ┆ 7.6        ┆ 0.359122   ┆ 4.046879   ┆ 4     │
│          ┆ 12 years a  ┆ Planet      ┆ Sci-Fi     ┆            ┆            ┆            ┆       │
│          ┆ slave bu…   ┆             ┆            ┆            ┆            ┆            ┆       │
│ 3        ┆ similar to  ┆ A           ┆ Action,Cri ┆ 7.5        ┆ 0.345881   ┆ 3.252245   ┆ 4     │
│          ┆ 12 years a  ┆ Bittersweet ┆ me,Drama   ┆            ┆            ┆            ┆       │
│          ┆ slave bu…   ┆ Life        ┆            ┆            ┆            ┆            ┆       │
│ 3        ┆ similar to  ┆ Vengeance   ┆ Crime,Dram ┆ 7.7        ┆ 0.367232   ┆ 2.083433   ┆ 4     │
│          ┆ 12 years a  ┆ Is Mine     ┆ a          ┆            ┆            ┆            ┆       │
│          ┆ slave bu…   ┆             ┆            ┆            ┆            ┆            ┆       │
│ 3        ┆ similar to  ┆ The         ┆ Drama,Roma ┆ 8.6        ┆ 0.343551   ┆ 1.787699   ┆ 4     │
│          ┆ 12 years a  ┆ Counterfeit ┆ nce        ┆            ┆            ┆            ┆       │
│          ┆ slave bu…   ┆ Coin        ┆            ┆            ┆            ┆            ┆       │
│ 3        ┆ similar to  ┆ The Fear of ┆ Biography, ┆ 7.6        ┆ 0.376941   ┆ 1.521223   ┆ 4     │
│          ┆ 12 years a  ┆ 13          ┆ Crime,Docu ┆            ┆            ┆            ┆       │
│          ┆ slave bu…   ┆             ┆ mentary    ┆            ┆            ┆            ┆       │
│ 3        ┆ similar to  ┆ In Time     ┆ Action,Sci ┆ 6.7        ┆ 0.328491   ┆ 1.493171   ┆ 4     │
│          ┆ 12 years a  ┆             ┆ -Fi,Thrill ┆            ┆            ┆            ┆       │
│          ┆ slave bu…   ┆             ┆ er         ┆            ┆            ┆            ┆       │
│ 3        ┆ similar to  ┆ Scum        ┆ Crime,Dram ┆ 7.5        ┆ 0.347279   ┆ 1.465569   ┆ 4     │
│          ┆ 12 years a  ┆             ┆ a          ┆            ┆            ┆            ┆       │
│          ┆ slave bu…   ┆             ┆            ┆            ┆            ┆            ┆       │
└──────────┴─────────────┴─────────────┴────────────┴────────────┴────────────┴────────────┴───────┘